# Generated by Django 4.1.1 on 2022-10-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passwords_name", models.CharField(max_length=80)),
                ("password_obj", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="PasswordsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passwords_name", models.CharField(max_length=30)),
                ("password_obj", models.CharField(max_length=50)),
            ],
        ),
    ]
